Repository enisn/Xamarin.Forms.InputKit, pull requests merged in 2021-04, with the labels that each got.

#210 Add BindableProperty for Dropdown Color
  InputKit/Shared/Controls/Dropdown.cs
Labels: enhancement, missing feature

#211 Repair BackgroundColor , Placeholder Properties in AdvancedEntry
  InputKit/Shared/Controls/AdvancedEntry.cs
Labels: enhancement

#213 ✨ Add Focused & Unfocused wrapper for AdvancedEntry
  InputKit/Shared/Controls/AdvancedEntry.cs
Labels: enhancement

#214 Monoandroid 11.0 Support
  InputKit/InputKit.csproj
  README.md
Labels: Android, feature
